from dataclasses import dataclass


@dataclass(frozen=True)
class ExcelColumns:
    DOCKET_LEVEL: str = "Docket Level/Subdocket Level"
    DOCKET_NUMBER: str = "Docket Number"
    TITLE: str = "Title"
    FILING_ENTITY_TYPE: str = "Filing Entity Type"
    FIRST_FILING_TYPE: str = "First Filing Type"
    CURRENT_STATUS: str = "Current Status"
    FOREIGN_FILING_COUNTRIES: str = "Foreign Filing Countries"
    MANAGER_INTERNAL: str = "Manager (Internal)"
    REVIEWER: str = "Reviewer"
    DRAFTER: str = "Drafter"
    FIRST_FILING_COUNTRY: str = "First Filing Country"
    FILING_MAINTENANCE_COST_ESTIMATE: str = "Filing & Maintenance Cost Estimate"
    DEADLINE_FOR_FILING: str = "Deadline for filing(Date)"
    ANNUITY_TIMELINE: str = "Annuity Timeline"
    CURRENT_STATUS_DATE: str = "Current Status Date"
    FIRST_FILING_DATE: str = "First Filing Date"
    SENT_FOR_REVIEW: str = "Sent For Review(Yes/No)"
    SENT_FOR_DRAFTING: str = "Sent for Drafting(Yes/No)"
    CLIENT: str = "Client"
    CLIENT_DIVISION: str = "Client Division"
    DEPARTMENT: str = "Department"
    ANALYST: str = "Analyst"
    PATENT_AGENT: str = "Patent Agent"
    INVENTORS: str = "Inventors"
    SUB_DOCKET_NUMBER: str = "Sub-Docket Number"
    TYPE_OF_FILING: str = "Type Of Filing"
    COUNTRY_OF_FILING: str = "Country Of Filing"
    PATENT_OFFICE_COUNTRY: str = "Patent Office(Country)"
    SUBDOCKET_FOREIGN_FILING_COUNTRIES: str = "Subdocket Foreign Filing Countries"
    STATUS: str = "Status"
    TYPE_OF_FILING_ENTITY: str = "Type of Filing Entity"
    APPLICATION_NUMBER: str = "Application Number"
    SUBDOCKET_FILING_MAINTENANCE_COST_ESTIMATE: str = (
        "Subdocket Filing & Maintenance Cost Estimate"
    )
    PUBLICATION_NUMBER: str = "Publication Number"
    ASSIGNEE_NAME: str = "Assignee Name"
    TENTATIVE_FILING_DATE: str = "Tentative Filing Date"
    PRIOR_FILING_DATE: str = "Prior Filing Date"
    PRIORITY_DATE: str = "Priority Date"
    FILING_DATE: str = "Filing Date"
    PUBLICATION_DATE: str = "Publication Date"
    GRANT_DATE: str = "Grant Date"
    EXPECTED_FILING_YEAR: str = "Expected Filing Year"
    RECENT_OA_RECEIVED_DATE: str = "Recent OA Received Date"
    INFORCE: str = "Inforce(Yes/No)"
    ANNUITY_FEE: str = "Annuity Fee"
    TERM_EXTENSION: str = "Term Extension"
    SENT_FOR_PROSECUTION: str = "Sent for Prosecution(Yes/No)"
    SENT_FOR_ANNUITY: str = "Sent for Annuity(Yes/No)"
