from sqlalchemy.orm import Session
from datetime import datetime
from decimal import Decimal
from models.pmv_csd_models import (
    Subdocket,
    SubdocketUserRolesMapping,
    SubdocketAssigneeMapping,
    ForeignFilingCountry,
    FilingType,
    SubdocketLogs,
    Countries,
    Assignee,
    User,
)
from models.invention_disclosure_models import Docket
import uuid
from services.utils.role_constants import RoleEnum
from services.utils.lookup_cache import (
    uuid_for_user_name,
    uuid_for_department,
    client_entry,
)

from excel.ExcelData import ExcelColumns
from services.logger import logger


def get_max_temp_number(session: Session) -> int:
    result = (
        session.query(Subdocket.temp_number)
        .order_by(Subdocket.temp_number.desc())
        .first()
    )
    return (result[0] + 1) if result and result[0] != 0 else 1


def get_autogenerated_subdocket_number(
    session: Session, row: dict, docket_number: str
) -> str:
    temp_number = get_max_temp_number(session)

    # --------- Filing Type Code ---------
    filing_type_name = row.get(ExcelColumns.TYPE_OF_FILING)
    if not filing_type_name:
        raise ValueError(
            "Missing 'Type Of Filing' in row – cannot generate subdocket number."
        )

    filing_type = session.query(FilingType).filter_by(name=filing_type_name).first()
    if not filing_type:
        raise ValueError(
            f"Invalid Filing Type: '{filing_type_name}' – cannot generate subdocket number."
        )
    filing_type_code = filing_type.code

    # --------- Country Code -------------
    country_name = row.get(ExcelColumns.COUNTRY_OF_FILING)
    if not country_name:
        raise ValueError(
            "Missing 'Country Of Filing' in row – cannot generate subdocket number."
        )

    country = session.query(Countries).filter_by(name=country_name).first()
    if not country:
        raise ValueError(
            f"Invalid Country Of Filing: '{country_name}' – cannot generate subdocket number."
        )
    country_code = country.code

    padded_temp = str(temp_number).zfill(4)
    return f"{docket_number}/{country_code}/{filing_type_code}/{padded_temp}"


def handle_assignees(
    session: Session, assignee_names: list[str], subdocket: Subdocket, user: User
) -> list[SubdocketAssigneeMapping]:
    mappings = []
    for name in assignee_names:
        name = name.strip()
        if not name:
            continue

        assignee = (
            session.query(Assignee)
            .filter_by(name=name, tenant_id=user.tenant_id)
            .first()
        )

        if not assignee:
            assignee = Assignee(
                name=name,
                client=subdocket.client,
                tenant_id=user.tenant_id,
                added_by=user,
                added_date=datetime.utcnow(),
            )
            session.add(assignee)
            session.flush()

        mapping = SubdocketAssigneeMapping(
            subdocket=subdocket,
            assignee=assignee,
            added_by=user,
            added_date=datetime.utcnow(),
        )
        session.add(mapping)
        mappings.append(mapping)

    return mappings


def save_subdocket(
    session: Session,
    ict_session,
    row: dict,
    docket_uuid: str,
    docket_number: str,
    tenant_id: str,
    import_user: str,
):

    docket = (
        ict_session.query(Docket)
        .filter(
            (Docket.manual_docket_number == docket_number)
            | (Docket.system_generated_docket_number == docket_number),
            Docket.tenant_id == tenant_id,
        )
        .first()
    )

    if not docket:
        logger.warning(
            f"Skipping subdocket save – docket '{docket_number}' not found in Invention Disclosure DB."
        )
        return

    client_name = row[ExcelColumns.CLIENT]
    dept_name = row[ExcelColumns.DEPARTMENT]
    div_name = row[ExcelColumns.CLIENT_DIVISION]

    client_info = client_entry(client_name)
    if not client_info:
        raise ValueError(f"Client not found in cache: {client_name}")

    client_uuid = client_info["uuid"]
    department_uuid = uuid_for_department(client_name, dept_name)

    if not department_uuid:
        raise ValueError(f"Department not found: {dept_name} for client {client_name}")

    subdocket = Subdocket(
        uuid=uuid.uuid4(),
        docket_uuid=docket_uuid,
        docket_number=docket_number,
        appid="80247b94-efdf-11ed-8f46-5a43ae00effd",
        tenant_id=tenant_id,
        added_by=import_user,
        added_date=datetime.utcnow(),
        archived=False,
    )

    subdocket.client_id = client_uuid
    subdocket.department_id = department_uuid

    subdocket.manual_subdocket_number = row.get(ExcelColumns.SUB_DOCKET_NUMBER)
    subdocket.system_generated_subdocket_number = get_autogenerated_subdocket_number(
        session, row, docket_number
    )
    subdocket.temp_number = get_max_temp_number(session)

    subdocket.application_number = row.get(ExcelColumns.APPLICATION_NUMBER)
    subdocket.publication_number = row.get(ExcelColumns.PUBLICATION_NUMBER)

    # Dates
    def parse_date(value):
        return datetime.strptime(value, "%Y-%m-%d") if value else None

    subdocket.tentative_filing_date = parse_date(
        row.get(ExcelColumns.TENTATIVE_FILING_DATE)
    )
    subdocket.prior_filing_date = parse_date(row.get(ExcelColumns.PRIOR_FILING_DATE))
    subdocket.priority_date = parse_date(row.get(ExcelColumns.PRIORITY_DATE))
    subdocket.filing_date = parse_date(row.get(ExcelColumns.FILING_DATE))
    subdocket.publication_date = parse_date(row.get(ExcelColumns.PUBLICATION_DATE))
    subdocket.grant_date = parse_date(row.get(ExcelColumns.GRANT_DATE))
    subdocket.expected_filing_year = (
        parse_date(str(row.get(ExcelColumns.EXPECTED_FILING_YEAR)))
        if row.get(ExcelColumns.EXPECTED_FILING_YEAR)
        else None
    )
    subdocket.recent_action_recieved_date = parse_date(
        row.get(ExcelColumns.RECENT_OA_RECEIVED_DATE)
    )
    subdocket.term_extention = parse_date(row.get(ExcelColumns.TERM_EXTENSION))

    if cost := row.get(ExcelColumns.FILING_MAINTENANCE_COST_ESTIMATE_SUB):
        try:
            subdocket.filing_maintenance_cost_estimate = Decimal(cost)
        except Exception:
            logger.warning(f"Invalid maintenance cost: {cost}")

    session.add(subdocket)
    session.flush()

    # Assignee logic
    assignee_names = [row.get(ExcelColumns.ASSIGNEE_NAME, "")]
    handle_assignees(session, assignee_names, subdocket, import_user)

    # Logs (optional)
    log = SubdocketLogs(
        subdocket=subdocket,
        client_id=subdocket.client_id,
        tenant_id=subdocket.tenant_id,
        added_by=import_user,
        added_date=datetime.utcnow(),
        logs="Subdocket Created",
    )
    session.add(log)

    logger.info(
        f"Subdocket saved: {subdocket.manual_subdocket_number} for docket: {docket_number}"
    )
